# -*- coding: utf-8 -*-
"""One

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aEYNgXp5hgOWBlyJofIBC62nBAcVQNY4
"""

print("Hello")

net_income = 50000
interest = 170
tax = 10
dep = 10
amor = 10

ebitda = net_income + interest + tax + dep + amor
print("EBITDA:", ebitda)

ebitda_margin = (ebitda / 1000000) * 100
print("EBITDA Margin:", ebitda_margin, "%")

net_income = 1000000
interest = 500
tax = 100
dep = 100
amor = 100

ebitda = net_income + interest + tax + dep + amor
ebitda_margin = (ebitda / net_income) * 100

debt = 3000000
leverage_ratio = debt / ebitda

print("EBITDA:", ebitda)
print("EBITDA Margin:", ebitda_margin, "%")
print("Leverage Ratio:", leverage_ratio, "x")

if leverage_ratio > 5:
    print("Warning: highly leveraged")
elif leverage_ratio > 3:
    print("Moderate leverage — monitor")
else:
    print("Leverage looks healthy")

def full_ebitda_analysis(company_name, revenue, net_income, interest, tax, dep, amor, debt, capex):

    ebitda = net_income + interest + tax + dep + amor
    ebit = ebitda - dep - amor
    ebitda_margin = (ebitda / revenue) * 100
    ebit_margin = (ebit / revenue) * 100
    leverage_ratio = debt / ebitda
    interest_coverage = ebitda / interest
    debt_payback = debt / (ebitda - capex)
    fcf = ebitda - capex - interest - tax   # free cash flow

    print(f"\n===== {company_name} =====")
    print(f"Revenue:            £{revenue:,}")
    print(f"EBITDA:             £{ebitda:,}")
    print(f"EBIT:               £{ebit:,}")
    print(f"EBITDA Margin:      {round(ebitda_margin, 2)}%")
    print(f"EBIT Margin:        {round(ebit_margin, 2)}%")
    print(f"Leverage Ratio:     {round(leverage_ratio, 2)}x")
    print(f"Interest Coverage:  {round(interest_coverage, 2)}x")
    print(f"Debt Payback:       {round(debt_payback, 2)} years")
    print(f"Free Cash Flow:     £{round(fcf):,}")

    print("\n--- Flags ---")
    if leverage_ratio > 5:
        print("⚠ Leverage: HIGH RISK")
    elif leverage_ratio > 3:
        print("~ Leverage: MODERATE")
    else:
        print("✓ Leverage: HEALTHY")

    if interest_coverage < 2:
        print("⚠ Interest Coverage: DANGER - may struggle to pay debt")
    elif interest_coverage < 3:
        print("~ Interest Coverage: TIGHT")
    else:
        print("✓ Interest Coverage: COMFORTABLE")

    if fcf < 0:
        print("⚠ Free Cash Flow: NEGATIVE")
    else:
        print("✓ Free Cash Flow: POSITIVE")


# EXM

full_ebitda_analysis(
    company_name="Irmaco",
    revenue=5000000,
    net_income=800000,
    interest=120000,
    tax=200000,
    dep=150000,
    amor=80000,
    debt=6000000,
    capex=300000
)